"""Data contracts shared by every layer of the pipeline.

This module is the spine of the project. It says nothing about *how* any
layer works -- only about the shape of the data that flows between them.
Implementations can be rewritten freely; these shapes should not change
without a deliberate decision.

Two families of types live here, and the split is intentional:

* **Frozen dataclasses** for internal pipeline data (Page, ParsedDocument,
  Chunk, EmbeddedChunk, RetrievedChunk). We construct these ourselves, so
  runtime validation would only cost cycles. Frozen means metadata can be
  *carried* but never *mutated* -- which is exactly the invariant the whole
  traceability feature depends on.

* **Pydantic models** for anything crossing a trust boundary -- namely the
  LLM's response (GeneratedItem, GeneratedExam). That data is generated by
  a model that may omit fields or invent shapes, so it must be validated,
  and pydantic doubles as the source of the JSON schema we constrain the
  model with.

Rule of thumb: pydantic at the boundary, dataclasses on the inside.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from pathlib import Path

from pydantic import BaseModel, Field

__all__ = [
    "Vector",
    "Page",
    "ParsedDocument",
    "Chunk",
    "EmbeddedChunk",
    "RetrievedChunk",
    "GeneratedItem",
    "GeneratedExam",
]


# An embedding. Length is model-dependent (bge-m3 gives 1024), which is why
# the dimension is probed at ingest time and recorded in the store's meta
# table rather than hard-coded anywhere.
Vector = list[float]


# ---------------------------------------------------------------------------
# Ingestion: layers 1-4
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Page:
    """One page of a source document, as produced by the Parser (layer 2).

    The page number is captured here and nowhere else. If it is lost at this
    point no downstream layer can reconstruct it, and citations die with it.
    """

    number: int  # 1-based, matching what a human sees in a PDF reader
    text: str


@dataclass(frozen=True, slots=True)
class ParsedDocument:
    """A single source file after text extraction (layer 2 output)."""

    source: str  # file name only, e.g. "lecture3.pdf" -- this is what gets cited
    pages: list[Page]

    @property
    def is_empty(self) -> bool:
        """True when extraction produced essentially nothing.

        Usually means the PDF is a scan with no text layer. The Parser should
        treat this as a hard failure rather than letting an empty document
        flow silently into the index.
        """
        return not any(page.text.strip() for page in self.pages)


@dataclass(frozen=True, slots=True)
class Chunk:
    """A retrievable unit of text (layer 3 output).

    Provenance is flattened onto every chunk on purpose: the chunk travels
    alone through embedding, storage and retrieval, so anything it does not
    carry itself is unrecoverable by the time an answer is written.
    """

    id: str  # deterministic, e.g. "lecture3_p12_c2" -- see make_id()
    text: str
    source: str
    page: int  # first page this chunk draws from
    page_end: int | None = None  # last page, when the chunk runs across a break
    section: str | None = None

    @staticmethod
    def make_id(source: str, page: int, index: int) -> str:
        """Build a stable chunk id.

        Determinism matters: re-ingesting an unchanged file must produce the
        same ids so that writes stay idempotent and a partly failed ingest
        repairs the index instead of duplicating it.

        The whole relative path is used, not just the file name. Course
        folders are routinely organised by week, and `week1/notes.md` and
        `week2/notes.md` are different documents -- collapsing them to
        "notes" made the second silently overwrite the first, losing an
        entire file's worth of material without any error.
        """
        path = Path(source)
        stem = "_".join([*path.parent.parts, path.stem]).strip("_") or path.stem
        return f"{stem}_p{page}_c{index}"

    @property
    def citation(self) -> str:
        """How this chunk is referred to in a prompt and in the final answer.

        A page range appears only when the chunk genuinely spans one, so the
        common case stays short and readable.
        """
        if self.page_end and self.page_end != self.page:
            return f"{self.source} pp{self.page}-{self.page_end}"
        return f"{self.source} p{self.page}"


@dataclass(frozen=True, slots=True)
class EmbeddedChunk:
    """A chunk plus its vector (layer 4 output).

    Composition rather than inheritance, so that `chunk` stays a plain Chunk
    and can be handed to the store, the prompt builder and the renderer
    without any of them knowing an embedding was ever attached.
    """

    chunk: Chunk
    embedding: Vector

    @property
    def dim(self) -> int:
        return len(self.embedding)


# ---------------------------------------------------------------------------
# Query: layers 6-7
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class RetrievedChunk:
    """A chunk returned by the Retriever, with its similarity score.

    The score is not shown to the user, but it is the single most useful
    number when retrieval quality is being debugged -- print the spread
    before blaming the prompt or the model.
    """

    chunk: Chunk
    score: float  # cosine similarity, 1.0 = identical direction, 0.0 = unrelated

    def with_score(self, score: float) -> RetrievedChunk:
        """Return a copy carrying a different score (e.g. after re-ranking)."""
        return replace(self, score=score)


# ---------------------------------------------------------------------------
# Generation output -- crosses a trust boundary, so pydantic
# ---------------------------------------------------------------------------


class GeneratedItem(BaseModel):
    """One question/answer pair produced by the LLM.

    `source` and `page` are required, and that is the whole point: the schema
    forces the model to name where each answer came from. A format-level
    constraint is enforceable in a way that "please do not make things up"
    in a prompt is not.
    """

    topic: str = Field(description="Two to five words naming what this tests.")
    question: str = Field(description="The exam question, self-contained.")
    answer: str = Field(description="The answer, grounded in the supplied material.")
    source: str = Field(description="File name the answer came from, e.g. lecture3.pdf")
    page: int = Field(description="Page number within that file.")


class GeneratedExam(BaseModel):
    """The full LLM response for a `mock` run.

    Deliberately flat -- a single list of items, no nesting by section or
    difficulty. Small local models follow simple schemas far more reliably,
    and the design principle is that the weakest supported model sets the
    shape while stronger ones satisfy it for free.

    `items` is required but may be empty, and the distinction is the whole
    point. Requiring at least one item forbids the only honest answer
    available when the material will not support a question -- that is how a
    system unable to say "this is not in the notes" ends up inventing
    something. But giving the field a *default* is just as wrong in the other
    direction: a reply of `{}`, or one using the model's own preferred key,
    then validates silently as "no questions found" when what actually
    happened was a malformed response nobody noticed.

    Required-but-emptiable separates the two: a missing key is an error worth
    retrying, an explicit empty list is an answer worth reporting.
    """

    items: list[GeneratedItem] = Field(
        description="One entry per question. Empty only if the material "
        "genuinely supports none."
    )
